//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBlog_Pascal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int ID { get; set; }
        public Nullable<int> REF_Thema { get; set; }
        public string Titel { get; set; }
        public string Text { get; set; }
        public string Autor { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
        public string Tags { get; set; }
    
        public virtual Theman Theman { get; set; }
    }
}
